# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmark',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
