# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bookmark',
            new_name='module_bookmark',
        ),
        migrations.AddField(
            model_name='profile',
            name='course_bookmark',
            field=models.CharField(default='the-strategy', max_length=100),
        ),
    ]
