# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('created',)},
        ),
    ]
