# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170405_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='paypal_button',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
