# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170421_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hola',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
