# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_questions'),
        ('orders', '0005_product_hola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hola',
        ),
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='courses.Course'),
        ),
    ]
